# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mahaldist <- function(x, y, w) {
    .Call('soilsecuritylab_mahaldist', PACKAGE = 'soilsecuritylab', x, y, w)
}

.fuzzy_extragrades_C <- function(alpha, data, phi, nclass, disttype, maxiter, toldif, exp_eg, optim) {
    .Call('soilsecuritylab_fuzzy_extragrades_C', PACKAGE = 'soilsecuritylab', alpha, data, phi, nclass, disttype, maxiter, toldif, exp_eg, optim)
}

