# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Calculate distances
#'
#'@param x matrix
#'@param y matrix
#'@param w matrix
#'@return distance matrix
mahaldist <- function(x, y, w) {
    .Call('soilsecuritylab_mahaldist', PACKAGE = 'soilsecuritylab', x, y, w)
}

#'Run fuzzy clustering algorithm
#'
#'@param alpha temp.
#'@param data a \code{data.frame} with numerical data. Each column corresponds to a dimension of a \code{n}-dimensional clustering domain.
#'@param phi a numerical value representing the degree of fuzziness or overlap of the generated clusters.
#'@param nclass numerical (integer) vector with the number of cluster to generate.
#'@param disttype numerical value representing the type of distance to calculate for the clustering. Possible values are: 1 (Euclidean), 2 (Diagonal), and 3 (default, Mahalanobis).
#'@param maxiter maximum number of iterations.
#'@param toldif temp.
#'@param exp_eg the expected fraction of extragrades. If not provided, it is assumed to be dependant on the number of clusters (\code{1/(1+nclusters)}).
#'@param optim temp.
#'@return \code{FuzzyClusterGroup}
.fuzzy_extragrades_C <- function(alpha, data, phi, nclass, disttype, maxiter, toldif, exp_eg, optim) {
    .Call('soilsecuritylab_fuzzy_extragrades_C', PACKAGE = 'soilsecuritylab', alpha, data, phi, nclass, disttype, maxiter, toldif, exp_eg, optim)
}

